//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Crud_Operation.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class testdbsanEntities : DbContext
    {
        public testdbsanEntities()
            : base("name=testdbsanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<UserRoleType> UserRoleTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
    
        public virtual ObjectResult<UserRoleTypesListHeirarchy_Result> UserRoleTypesListHeirarchy()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<UserRoleTypesListHeirarchy_Result>("UserRoleTypesListHeirarchy");
        }
    }
}
